export const documentFields = [
    { id: 1, name: "Resume", submitted: false, file: null },
    { id: 2, name: "PERPETUUITI Offer Letter", submitted: false, file: null },
    { id: 3, name: "Birth Date Proof", submitted: false, file: null },
    { id: 4, name: "Address Proof", submitted: false, file: null },
    { id: 5, name: "S.S.C Certificate", submitted: false, file: null },
    { id: 6, name: "H.S.C Certificate", submitted: false, file: null },
    { id: 7, name: "Graduation Certificate/Mark Sheet", submitted: false, file: null },
    { id: 8, name: "Post-Graduation Certificate/Mark Sheet", submitted: false, file: null },
    { id: 9, name: "Relieving Letter from Previous Employer", submitted: false, file: null },
    { id: 10, name: "Last 3 Months' Salary Slips", submitted: false, file: null },
    { id: 11, name: "Copy of Passport (if available)", submitted: false, file: null },
    { id: 12, name: "Copy of PAN Card", submitted: false, file: null },
    { id: 13, name: "Driving License/Aadhar Card", submitted: false, file: null },
    { id: 14, name: "2 Colored Passport-Size Photos (Current)", submitted: false, file: null },
    { id: 15, name: "NDA", submitted: false, file: null },
    { id: 16, name: "Non-Compete Agreement", submitted: false, file: null },
    { id: 17, name: "Appraisal Letter", submitted: false, file: null },
    { id: 18, name: "Form 16 Copy", submitted: false, file: null },
    { id: 19, name: "Bank Passbook Copy", submitted: false, file: null },
    { id: 20, name: "PF Passbook Copy", submitted: false, file: null },
  ]