
export const documentFields = [
    { id: 1, name: "Resume", submitted: false, file: null },
    { id: 2, name: "PERPETUUITI Offer Letter", submitted: false, file: null },
    { id: 3, name: "Birth Date Proof", submitted: false, file: null },
    { id: 4, name: "Address Proof", submitted: false, file: null },
    { id: 5, name: "S.S.C Certificate", submitted: false, file: null },
    { id: 6, name: "H.S.C Certificate", submitted: false, file: null },
    { id: 7, name: "Graduation Certificate/Mark Sheet", submitted: false, file: null },
    { id: 8, name: "Post-Graduation Certificate/Mark Sheet", submitted: false, file: null },
    { id: 9, name: "Relieving Letter from Previous Employer", submitted: false, file: null },
    { id: 10, name: "Last 3 Months' Salary Slips", submitted: false, file: null },
    { id: 11, name: "Copy of Passport (if available)", submitted: false, file: null },
    { id: 12, name: "Copy of PAN Card", submitted: false, file: null },
    { id: 13, name: "Driving License/Aadhar Card", submitted: false, file: null },
    { id: 14, name: "2 Colored Passport-Size Photos (Current)", submitted: false, file: null },
    { id: 15, name: "NDA", submitted: false, file: null },
    { id: 16, name: "Non-Compete Agreement", submitted: false, file: null },
    { id: 17, name: "Appraisal Letter", submitted: false, file: null },
    { id: 18, name: "Form 16 Copy", submitted: false, file: null },
    { id: 19, name: "Bank Passbook Copy", submitted: false, file: null },
    { id: 20, name: "PF Passbook Copy", submitted: false, file: null },
  ];

  export const entries = [
    {
      id: '4f5bedd696b8',
      Name: 'Sam John',
      DOJ: '21-Oct-2024',
      Department: 'Finance',
      userName: 'john21',
      password: 'welcome21',
      documents: [
        { id: 1, name: "Resume", submitted: true, file: 'assets/Form.pdf' },
        { id: 2, name: "PERPETUUITI Offer Letter", submitted: true, file: 'assets/Form.pdf' },
        { id: 3, name: "Birth Date Proof", submitted: true, file: 'assets/Form.pdf' },
        { id: 4, name: "Address Proof", submitted: true, file: 'assets/Form.pdf' },
        { id: 5, name: "S.S.C Certificate", submitted: true, file: 'assets/Form.pdf' },
        { id: 6, name: "H.S.C Certificate", submitted: true, file: 'assets/Form.pdf' },
        { id: 7, name: "Graduation Certificate/Mark Sheet", submitted: true, file: 'assets/Form.pdf' },
        { id: 8, name: "Post-Graduation Certificate/Mark Sheet", submitted: true, file: 'assets/Form.pdf' },
        { id: 9, name: "Relieving Letter from Previous Employer", submitted: true, file: 'assets/Form.pdf' },
        { id: 10, name: "Last 3 Months' Salary Slips", submitted: true, file: 'assets/Form.pdf' },
        { id: 11, name: "Copy of Passport (if available)", submitted: true, file: 'assets/Form.pdf' },
        { id: 12, name: "Copy of PAN Card", submitted: true, file: 'assets/Form.pdf' },
        { id: 13, name: "Driving License/Aadhar Card", submitted: true, file: 'assets/Form.pdf' },
        { id: 14, name: "2 Colored Passport-Size Photos (Current)", submitted: true, file: 'assets/Form.pdf' },
        { id: 15, name: "NDA", submitted: true, file: 'assets/Form.pdf' },
        { id: 16, name: "Non-Compete Agreement", submitted: true, file: 'assets/Form.pdf' },
        { id: 17, name: "Appraisal Letter", submitted: true, file: 'assets/Form.pdf' },
        { id: 18, name: "Form 16 Copy", submitted: true, file: 'assets/Form.pdf' },
        { id: 19, name: "Bank Passbook Copy", submitted: true, file: 'assets/Form.pdf' },
        { id: 20, name: "PF Passbook Copy", submitted: true, file: 'assets/Form.pdf' },
      ]
    },
    {
      id: '0d697c8f2e16',
      Name: 'Alex Smith',
      DOJ: '15-Sep-2024',
      Department: 'Marketing',
      userName: 'smith15',
      password: 'welcome15',
      documents: [
        { id: 1, name: "Resume", submitted: false, file: null },
        { id: 2, name: "PERPETUUITI Offer Letter", submitted: false, file: null },
        { id: 3, name: "Birth Date Proof", submitted: false, file: null },
        { id: 4, name: "Address Proof", submitted: false, file: null },
        { id: 5, name: "S.S.C Certificate", submitted: false, file: null },
        { id: 6, name: "H.S.C Certificate", submitted: false, file: null },
        { id: 7, name: "Graduation Certificate/Mark Sheet", submitted: false, file: null },
        { id: 8, name: "Post-Graduation Certificate/Mark Sheet", submitted: false, file: null },
        { id: 9, name: "Relieving Letter from Previous Employer", submitted: false, file: null },
        { id: 10, name: "Last 3 Months' Salary Slips", submitted: false, file: null },
        { id: 11, name: "Copy of Passport (if available)", submitted: false, file: null },
        { id: 12, name: "Copy of PAN Card", submitted: false, file: null },
        { id: 13, name: "Driving License/Aadhar Card", submitted: false, file: null },
        { id: 14, name: "2 Colored Passport-Size Photos (Current)", submitted: false, file: null },
        { id: 15, name: "NDA", submitted: false, file: null },
        { id: 16, name: "Non-Compete Agreement", submitted: false, file: null },
        { id: 17, name: "Appraisal Letter", submitted: false, file: null },
        { id: 18, name: "Form 16 Copy", submitted: false, file: null },
        { id: 19, name: "Bank Passbook Copy", submitted: false, file: null },
        { id: 20, name: "PF Passbook Copy", submitted: false, file: null },
      ]
    },
    {
      id: '7c82d87d60d0',
      Name: 'Lucy Brown',
      DOJ: '12-Aug-2024',
      Department: 'IT',
      userName: 'brown12',
      password: 'welcome12',
      documents: [
        { id: 1, name: "Resume", submitted: true, file: 'assets/Form.pdf' },
        { id: 2, name: "PERPETUUITI Offer Letter", submitted: true, file: 'assets/Form.pdf' },
        { id: 3, name: "Birth Date Proof", submitted: false, file: null },
        { id: 4, name: "Address Proof", submitted: false, file: null },
        { id: 5, name: "S.S.C Certificate", submitted: true, file: 'assets/Form.pdf' },
        { id: 6, name: "H.S.C Certificate", submitted: true, file: 'assets/Form.pdf' },
        { id: 7, name: "Graduation Certificate/Mark Sheet", submitted: false, file: null },
        { id: 8, name: "Post-Graduation Certificate/Mark Sheet", submitted: false, file: null },
        { id: 9, name: "Relieving Letter from Previous Employer", submitted: true, file: 'assets/Form.pdf' },
        { id: 10, name: "Last 3 Months' Salary Slips", submitted: true, file: 'assets/Form.pdf' },
        { id: 11, name: "Copy of Passport (if available)", submitted: false, file: null },
        { id: 12, name: "Copy of PAN Card", submitted: false, file: null },
        { id: 13, name: "Driving License/Aadhar Card", submitted: true, file: 'assets/Form.pdf' },
        { id: 14, name: "2 Colored Passport-Size Photos (Current)", submitted: true, file: 'assets/Form.pdf' },
        { id: 15, name: "NDA", submitted: false, file: null },
        { id: 16, name: "Non-Compete Agreement", submitted: false, file: null },
        { id: 17, name: "Appraisal Letter", submitted: true, file: 'assets/Form.pdf' },
        { id: 18, name: "Form 16 Copy", submitted: true, file: 'assets/Form.pdf' },
        { id: 19, name: "Bank Passbook Copy", submitted: false, file: null },
        { id: 20, name: "PF Passbook Copy", submitted: false, file: null },
      ]
    }
  ];
  